config/routes.rb
# == Route Map
#
#           Prefix Verb   URI Pattern                  Controller#Action
#             root GET    /                            static_pages#root
#            users POST   /users(.:format)             users#create
#         new_user GET    /users/new(.:format)         users#new
#             user GET    /users/:id(.:format)         users#show
#          session POST   /session(.:format)           sessions#create
#      new_session GET    /session/new(.:format)       sessions#new
#                  DELETE /session(.:format)           sessions#destroy
#    api_locations GET    /api/locations(.:format)     api/locations#index {:format=>:json}
#                  POST   /api/locations(.:format)     api/locations#create {:format=>:json}
# new_api_location GET    /api/locations/new(.:format) api/locations#new {:format=>:json}
#     api_location GET    /api/locations/:id(.:format) api/locations#show {:format=>:json}
#

Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :locations, only: [:index, :show, :create, :new]
  end
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id           :integer          not null, primary key
#  description  :string           not null
#  lat          :float            not null
#  lng          :float            not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  occupancy    :integer          not null
#  full_address :string           not null
#  title        :string           not null
#  image        :string           not null
#  price        :integer          not null
#  link         :string
#

class Location < ActiveRecord::Base
  validates :description, :lat, :lng, presence: true

  # has_many :location_images


  def self.in_bounds(bounds)
    # {
    #    "northEast"=> {"lat"=>"37.80971", "lng"=>"-122.39208"},
    #    "southWest"=> {"lat"=>"37.74187", "lng"=>"-122.47791"}
    # }
    rightb = bounds["northEast"]["lng"].to_f
    leftb = bounds["southWest"]["lng"].to_f
    topb = bounds["northEast"]["lat"].to_f
    bottomb = bounds["southWest"]["lat"].to_f
    locations_in_bound = []

    locations = Location.all
    locations.each do |location|
      if location.lat < topb && location.lat > bottomb && location.lng > leftb && location.lng < rightb
        locations_in_bound << location
      end
    end

    return locations_in_bound
  end



end

app/models/location_image.rb
# == Schema Information
#
# Table name: location_images
#
#  id          :integer          not null, primary key
#  location_id :integer          not null
#  image_url   :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class LocationImage < ActiveRecord::Base
  # validates :location_id, :image_url, presence: true
  #
  # belongs_to :location

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  first_name      :string
#  last_name       :string
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#


class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}


  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    # debugger
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/api/locations_controller.rb
class Api::LocationsController < ApplicationController
  def index
    if (params[:bounds])
      # debugger
      @locations = Location.in_bounds(params[:bounds])
    else
      @locations = Location.all
    end
  end

  def show
    if (params[:id])
      @location = Location.where(id: params[:id]).first
    else
      @location = nil
    end
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      render json: @location
    else
      # debugger
      render json: {error: "Invalid parameters"}
    end
  end

  def location_params
    params.require(:location).permit(:title, :description, :lat, :lng, :occupancy, :link, :price, :image, :full_address)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :require_signed_in!

  private
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid email or password"]
      render :new
    end
  end

  def destroy
    sign_out
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:password, :email)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :require_signed_in!

  def root

  end
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  first_name      :string
#  last_name       :string
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      # fail
      redirect_to "/"
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :email)
  end
end

app/helpers/api/locations_helper.rb
module Api::LocationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  first_name      :string
#  last_name       :string
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>
    <script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyD3-I1sq4rarS1K3i7DGjEwVBXfq8zCdpU"></script>
    <!-- MUI -->
    <link href="//cdn.muicss.com/mui-0.4.7/css/mui.min.css" rel="stylesheet" type="text/css" />
    <script src="//cdn.muicss.com/mui-0.4.7/js/mui.min.js"></script>
    <!-- End MUI -->
    <!-- Google Material Design -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
    <!-- End Google Material Design -->

<!-- Prevents Accidental Enter-Key Submission-->
    <script type="text/javascript">

    function stopRKey(evt) {
      var evt = (evt) ? evt : ((event) ? event : null);
      var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null);
      if ((evt.keyCode == 13) && (node.type=="text"))  {return false;}
    }

    document.onkeypress = stopRKey;

    </script>

    <!-- End enter key bug protocol -->

    <link rel="shortcut icon" type="image/x-icon" href="https://40.media.tumblr.com/34235ccd0f689feead5a9e4dbf68bcc3/tumblr_o3n99nAnMD1v497yzo1_75sq.png">



    <style type="text/css">
      html, body { height: 100%; margin: 0; padding: 0; }
      .map { height: 400px; width: 400px}
      .mapAddress { height: 400px; width: 400px }
    </style>

    <title>ScareBnb</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
     <%= flash[:errors].join("<br>").html_safe if flash[:errors] %>
     <%= yield %>
     Created by Benjamin Zagorski.  Github can be found <a href="https://github.com/mrmicrowaveoven/scarebnb">here</a>, Portfolio can be found <a href="http://benjzagorski.online/">here</a>.
  </body>
</html>

app/views/static_pages/root.html.erb
<div id="content"></div>
<script>
    {window.currentUserEmail = "<%= current_user.email %>";}
</script>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <%#= auth_token_input %>
  <label>
    Email
    <input type="text" name="user[email]" value="">
  </label>

  <label>
    Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">
</form>